use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Client {
    pub id: String,
    pub name: String,
    pub secret_hash: Option<String>,
    pub application_type: String,
    pub token_endpoint_auth_method: String,
    pub grant_types: Vec<String>,
    pub response_types: Vec<String>,
    pub redirect_uris: Vec<String>,
    pub post_logout_redirect_uris: Vec<String>,
    pub scope: Option<String>,
    pub contacts: Vec<String>,
    pub logo_uri: Option<String>,
    pub client_uri: Option<String>,
    pub policy_uri: Option<String>,
    pub tos_uri: Option<String>,
    pub jwks_uri: Option<String>,
    pub jwks: Option<serde_json::Value>,
    pub subject_type: Option<String>,
    pub sector_identifier_uri: Option<String>,
    pub owner_user_id: Option<String>,
    pub require_pkce: bool,
    pub first_party: bool,
    pub allowed_cors_origins: Vec<String>,
    pub client_id_issued_at: DateTime<Utc>,
    pub client_secret_expires_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClientPublic {
    pub id: String,
    pub name: String,
    pub application_type: String,
    pub token_endpoint_auth_method: String,
    pub grant_types: Vec<String>,
    pub response_types: Vec<String>,
    pub redirect_uris: Vec<String>,
    pub post_logout_redirect_uris: Vec<String>,
    pub scope: Option<String>,
    pub contacts: Vec<String>,
    pub logo_uri: Option<String>,
    pub client_uri: Option<String>,
    pub policy_uri: Option<String>,
    pub tos_uri: Option<String>,
    pub jwks_uri: Option<String>,
    pub subject_type: Option<String>,
    pub sector_identifier_uri: Option<String>,
    pub owner_user_id: Option<String>,
    pub require_pkce: bool,
    pub first_party: bool,
    pub allowed_cors_origins: Vec<String>,
    pub client_id_issued_at: DateTime<Utc>,
    pub client_secret_expires_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

impl From<Client> for ClientPublic {
    fn from(c: Client) -> Self {
        ClientPublic {
            id: c.id,
            name: c.name,
            application_type: c.application_type,
            token_endpoint_auth_method: c.token_endpoint_auth_method,
            grant_types: c.grant_types,
            response_types: c.response_types,
            redirect_uris: c.redirect_uris,
            post_logout_redirect_uris: c.post_logout_redirect_uris,
            scope: c.scope,
            contacts: c.contacts,
            logo_uri: c.logo_uri,
            client_uri: c.client_uri,
            policy_uri: c.policy_uri,
            tos_uri: c.tos_uri,
            jwks_uri: c.jwks_uri,
            subject_type: c.subject_type,
            sector_identifier_uri: c.sector_identifier_uri,
            owner_user_id: c.owner_user_id,
            require_pkce: c.require_pkce,
            first_party: c.first_party,
            allowed_cors_origins: c.allowed_cors_origins,
            client_id_issued_at: c.client_id_issued_at,
            client_secret_expires_at: c.client_secret_expires_at,
            created_at: c.created_at,
            updated_at: c.updated_at,
        }
    }
}
